all:
	@echo Must specify host name

.PHONY: bilbo
bilbo:
	HOST=bilbo ./run.sh
	git status -sb

.PHONY: arwen
arwen:
	HOST=arwen ./run.sh
	git status -sb

.PHONY: pippin
pippin:
	HOST=pippin ./run.sh
	git status -sb
