{ pkgs, lib, ... }:
{
  imports = [
    # Generated by nixos-generate-config on the machine; kept at /etc/nixos.
    /etc/nixos/hardware-configuration.nix
    ./common.nix
  ];

  system.stateVersion = "25.11";

  networking.hostName = "shire";
  networking.networkmanager.enable = true;
  time.timeZone = "America/New_York";

  # Plain x86_64 UEFI, single-OS box. systemd-boot also writes the
  # \EFI\BOOT\BOOTX64.EFI fallback path, which this GMKTec firmware needs.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # AMD Ryzen.
  hardware.cpu.amd.updateMicrocode = true;
  nixpkgs.config.allowUnfree = true;

  # Compressed RAM swap - faster than disk swap, provides a buffer before OOM.
  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # WireGuard VPN server. (migrated from pippinix)
  #
  # Off-LAN reachability depends on infra NOT in this repo:
  #   - home.blaix.com is a CNAME to the eero's dyndns hostname (tracks our
  #     dynamic home IP).
  #   - The eero forwards UDP 51820 to shire's LAN IP. That IP MUST be pinned
  #     with a DHCP reservation on the eero (do this in the eero app);
  # Peer client tunnels use Endpoint = home.blaix.com:51820 (set in each
  # device's WireGuard app, not declared here).
  networking.wireguard.interfaces.wg0 = {
    ips = [ "10.100.0.1/24" ];
    listenPort = 51820;
    generatePrivateKeyFile = true;
    privateKeyFile = "/etc/wireguard/wg0-key";

    peers = [
      { # arwen
        publicKey = "DnDZDE3WEygq58ak+ViZyRyp1sadqRKSmtoL25ztxiY=";
        allowedIPs = [ "10.100.0.2/32" ];
      }
      { # bilbo
        publicKey = "doShLIrZi005B0qsO8aLY4gF06gHSiv4Hw3YmnIe3Co=";
        allowedIPs = [ "10.100.0.3/32" ];
      }
      { # ipad
        publicKey = "j+PtMQZe4IBzTOjSCFeknomeeEZXAYd4rhfrX+GQJRQ=";
        allowedIPs = [ "10.100.0.4/32" ];
      }
      { # iphone
        publicKey = "MAqyNsojFlFxD0lbRzcT9d8/ZbeD7TyxWmOUR6EtNUk=";
        allowedIPs = [ "10.100.0.5/32" ];
      }
    ];
  };

  # Firewall - SSH, local dev servers, media servers (Jellyfin, Navidrome,
  # Komga, podcast Caddy), and WireGuard; trust the VPN interface. UDP 7359 is
  # Jellyfin client auto-discovery.
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 3000 8000 8080 8096 4533 25600 ];
    allowedUDPPorts = [ 51820 7359 ];
    trustedInterfaces = [ "wg0" ];
  };

  # Enable mosh connections (opens UDP ports)
  programs.mosh.enable = true;

  environment.systemPackages = [
    # cbr2cbz: convert RAR-based comic archives (which Komga struggles with) into .cbz.
    (pkgs.callPackage ../../pkgs/cbr2cbz.nix {})
    # sort-media: rename/move movie & tv files into a Jellyfin-friendly layout
    (pkgs.callPackage ../../pkgs/sort-media.nix {})
  ];

  # Jellyfin TV/movies server. Reachable on the LAN (8096). UDP 7359 is opened
  # above so LAN clients like the Roku Jellyfin app can auto-discover the server.
  services.jellyfin = {
    enable = true;
    openFirewall = false;
  };

  # Navidrome music server, reachable on the LAN (4533).
  services.navidrome = {
    enable = true;
    openFirewall = false;
    settings = {
      MusicFolder = "/mnt/media/music";
      Address = "0.0.0.0";
      Port = 4533;
      Plugins = {
        Enabled = true;
        Folder =
          let
            listenbrainz-daily-playlist = pkgs.fetchurl {
              url = "https://github.com/kgarner7/navidrome-listenbrainz-daily-playlist/releases/download/v5.0.2/listenbrainz-daily-playlist.ndp";
              hash = "sha256-P1lB18Gjqjg6p2atn+PqQRcM0U1jSCtGWqkZDNWQ3Pk=";
            };
          in
          pkgs.linkFarm "navidrome-plugins" [
            {
              name = "listenbrainz-daily-playlist.ndp";
              path = listenbrainz-daily-playlist;
            }
          ];
      };
    };
  };

  # Komga comics server, reachable on the LAN (25600). Reads the drive only;
  # content is added over ssh (rsync/scp) as justin.
  services.komga = {
    enable = true;
    openFirewall = false;
    settings.server.port = 25600;
  };

  # Private podcast server.
  services.caddy = {
    enable = true;
    virtualHosts.":8080" = {
      extraConfig = ''
        root * /mnt/media/podcasts
        file_server browse
      '';
    };
  };

  # Media libraries on the dedicated 8 TB USB drive (whole-disk ext4, label "media").
  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-label/media";
    fsType = "ext4";
    # nofail = server still boots if the drive is unplugged.
    options = [ "nofail" "noatime" "x-systemd.device-timeout=10s" ];
  };

  # Services read their libraries from this mount, so start them only after it
  # is mounted. Otherwise they capture a pre-mount namespace and see an empty
  # /mnt/media.
  systemd.services.navidrome = { after = [ "mnt-media.mount" ]; requires = [ "mnt-media.mount" ]; };
  systemd.services.jellyfin  = { after = [ "mnt-media.mount" ]; requires = [ "mnt-media.mount" ]; };
  systemd.services.komga     = { after = [ "mnt-media.mount" ]; requires = [ "mnt-media.mount" ]; };
  systemd.services.caddy     = { after = [ "mnt-media.mount" ]; requires = [ "mnt-media.mount" ]; };

  # The whole media drive is owned by justin and world-readable: the services
  # read as "other" and never write here. Content is added over ssh as justin.
  systemd.tmpfiles.rules = [
    "d /mnt/media          0755 justin justin -"
    "d /mnt/media/music    0755 justin justin -"
    "d /mnt/media/inbox    0755 justin justin -"
    "d /mnt/media/movies   0755 justin justin -"
    "d /mnt/media/tv       0755 justin justin -"
    "d /mnt/media/comics   0755 justin justin -"
    "d /mnt/media/podcasts 0755 justin justin -"
  ];

  # SMB share reachable from Macs as smb://shire.local (read-write).
  #
  # First-time machine setup (not declarative):
  #   - sudo smbpasswd -a justin to set the Samba password.
  #   - In Jellyfin's web UI, add libraries:
  #       Movies -> /mnt/media/movies   (do NOT include /mnt/media/inbox)
  #       Shows  -> /mnt/media/tv
  #     Leave "save artwork / NFO / subtitles into media folders" OFF.
  #   - In Navidrome's web UI, complete first-run admin setup.
  #   - In Komga's web UI (port 25600), create the admin account, then add a
  #     library pointing at /mnt/media/comics. Leave "write metadata back to
  #     files" / cover-persistence OFF.
  services.samba = {
    enable = true;
    openFirewall = true;
    settings = {
      global = {
        "workgroup" = "WORKGROUP";
        "server string" = "shire";
        "netbios name" = "shire";
        "security" = "user";
        # No anonymous access; we want auth so Finder caches creds in Keychain.
        "guest account" = "nobody";
        "map to guest" = "never";

        # macOS interop: store Mac metadata in ext4 xattrs instead of "._"
        # AppleDouble sidecar files, and auto-delete Finder/Spotlight junk.
        "vfs objects" = "catia fruit streams_xattr";
        "fruit:metadata" = "stream";
        "fruit:posix_rename" = "yes";
        "fruit:veto_appledouble" = "no";
        "fruit:wipe_intentionally_left_blank_rfork" = "yes";
        "fruit:delete_empty_adfiles" = "yes";
        "fruit:nfs_aces" = "no";
        "veto files" = "/.DS_Store/.Spotlight-V100/.Trashes/.TemporaryItems/.fseventsd/.apdisk/.AppleDB/.AppleDesktop/Network Trash Folder/Temporary Items/";
        "delete veto files" = "yes";
      };
      # Read-write share over the whole drive. Files are forced to justin and
      # world-readable so navidrome/jellyfin, which read as "other", can see
      # newly added content.
      media = {
        "path" = "/mnt/media";
        "browseable" = "yes";
        "read only" = "no";
        "guest ok" = "no";
        "valid users" = "justin";
        "force user" = "justin";
        "create mask" = "0644";
        "directory mask" = "0755";
      };
    };
  };

  # mDNS so this machine is reachable as shire.local
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
      userServices = true;          # required for extraServiceFiles
    };
    # so shire appears in the Finder Network sidebar automatically:
    extraServiceFiles.smb = ''
      <?xml version="1.0" standalone='no'?>
      <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
      <service-group>
        <name replace-wildcards="yes">%h</name>
        <service>
          <type>_smb._tcp</type>
          <port>445</port>
        </service>
      </service-group>
    '';
  };

  # Justin user configuration
  users.groups.justin = {};
  users.users.justin = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    group = "justin";
    openssh.authorizedKeys.keys = import ../../users/justin/ssh-keys.nix;
  };

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      X11Forwarding = false;
    };
  };
}
